server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  #############################新增网关配置###########################
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #写死的地址  匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址  动态路由
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
            # 这个时间后才能访问  秒杀之类的
            - After=2021-02-22T15:51:37.485+08:00[Asia/Shanghai]
            # 这个时间前才能访问  秒杀之类的
            # - Before=2021-02-22T15:51:37.485+08:00[Asia/Shanghai]
            # 两个时间点之间
            # - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates: # 说白了，Predicate就是为了实现一组匹配规则，让请求过来找到对应的Route进行处理。
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            # Cookie匹配cookie参数
            # 在cmd执行 curl http://localhost:9527/payment/lb --cookie "chocolate=chip"
            # . 小数点是单字符匹配
            # - Cookie=chocolate, ch..p
            # - Cookie=username, tanghao

            # 请求头需要X-Request-Id属性 且值为整数
            # 在cmd执行 curl http://localhost:9527/payment/lb -H "X-Request-Id:123"
            # curl http://localhost:9527/payment/lb -H "X-Request-Id:123" --cookie "username=tanghao"
            # - Header=X-Request-Id, \d+ #

            # curl http://localhost:9527/payment/lb -H "Host:www.atfuifu.com"
            # - Host=**.atfuifu.com

            # - Method=GET

            # curl http://localhost:9527/payment/lb?username=31
            # - Query=username, \d+
####################################################################

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
